### ISSUE TITLE
Internal3D

### ISSUE THREAD

**Issue by cdj1712** [aL3x-O-o-Hung/CSAM#1]
The function 'Internal3D' is not found.Can you help me? Thank you

**Comment by aL3x-O-o-Hung** [comment]
Hi, this is the dataloader that you need to implement.

**Comment by aL3x-O-o-Hung** [comment]
Also, the paper is not out yet. Please wait till the paper is officially published to see more details. Thanks!

**Comment by cdj1712** [comment]
> Also, the paper is not out yet. Please wait till the paper is officially published to see more details. Thanks!

Thank you for your excellent work. It helps me a lot. I would like to know what 'mask_onehot' is used for and how can I get it, thank you
