### ISSUE TITLE
PCa seg dataset

### ISSUE THREAD

**Issue by Happy-life-echo** [aL3x-O-o-Hung/CSAM#2]
This article of yours is also amazing! But I would like to know which dataset you used in prostate cancer segmentation? Is it https://pi-cai.grand-challenge.org/ ? 

I would be very grateful if you could let me know.🫡

**Comment by aL3x-O-o-Hung** [comment]
Hi! Thanks for the interest in our paper. Actually for PCa segmentation we used our internal dataset, but we are planning on including ProstateX in our future works.
