### ISSUE TITLE
What is the rank parameter in the SliceAttentionModule based on？

### ISSUE THREAD

**Issue by Breeze-Zero** [aL3x-O-o-Hung/CSAM#3]
What is the rank parameter in the SliceAttentionModule based on, does it default to 5 regardless of the number of slices?

**Comment by aL3x-O-o-Hung** [comment]
Thanks for the question and the interest in our work. Yes, it defaults to 5 in our implementation. In practice, I do think the number should be larger if the discrepancy between the in-plane and through-plane resolution is smaller, i.e. if the volume is more isotropic. However, the rank parameter is not a hyperparameter that we spent a lot of time tuning. The method should work better if the parameter is better tuned but I doubt the difference would be significant. Please let me know if you have further questions.
