### ISSUE TITLE
No dataloader is provided

### ISSUE THREAD

**Issue by lyt-cloud** [aL3x-O-o-Hung/CSAM#4]
Hi, I looked at your code and found that it is not complete,
For example, in the case of experiment.py
 "   for batch_num,data in enumerate(dataloader):
        img,mask,mask_onehot,length=data['im'],data['mask'],data['m'],data['length']"
Not sure how your dataloader is implemented

**Comment by lyt-cloud** [comment]
Could you please provide the complete code?

**Comment by aL3x-O-o-Hung** [comment]
Thanks for the interest in our work. Since a lot of the data we used is private, we are not planning on releasing the code for the dataloader since there is no point in doing so. However, the returned image shape should be batch_size x num_slices x num_channels x height x width. Hope this helps!
